In [1]:
#importing the modules
import os
import pandas as pd

In [32]:
home_dir=os.path.join(r'Z:\balint\numt/')

In [33]:
numts=pd.read_csv(home_dir+r'Michael/data/numt_master_array.csv',
                 index_col=0)
numts.head()

,eg2_value,e_value,g_id,g_start,mt_start,g_length,mt_length,g_strand,mt_strand,g_size,g_sequence,mt_sequence,g_up_flanking,g_down_flanking,"mt_up_flanking (if strand is negative, the coordinates are corrected)","mt_down_flanking (if strand is negative, the coordinates are corrected)",ensembl_gene_id,ensembl_description
score,,,,,,,,,,,,,,,,,,
17245,0.0,0.0,MT,0,0,17245,17245,+,+,17245,GTTAATGTAGCTTAACAACAAAGCAAAGCACTGAAAATGCTTAGAT...,GTTAATGTAGCTTAACAACAAAGCAAAGCACTGAAAATGCTTAGAT...,NaN,NaN,TACAAATTGTATAATATTTGGACTAAACCCCCTTTCCCACCCCAAG...,GTTAATGTAGCTTAACAACAAAGCAAAGCACTGAAAATGCTTAGAT...,ENSOCUG00000029081,NaN
3398,0.0,0.0,1,114731432,6976,4680,4681,+,+,194850757,taGTAAAATTATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,TAGTAAAACCATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,ACAAAAGACTCTGAATAGCCAAAGCGATCCTGAACAAGAAAAATCA...,TATATATATTTATATATATATGTATATATGTACATATATATAACTA...,CCTTCGCCTCAAAACGAGAAGTAGAGACTATTGAACTAACAACCAC...,AACTGCTAATTCATGCTCCCATGTCTAACCCCATGGCTTTCTCAAC...,ENSOCUG00000006104,cilia and flagella associated protein 300 [Sou...
3120,0.0,0.0,GL019308,67160,883,4892,4945,+,+,88228,CAAGGCCATGAAGCATGCACACACTGCCCATCGCTCTCCTCAAACA...,CAAGGCCATGAAGCACGCACACACCGCCCGTCACCCTCCTCAAGTG...,GATAAACCCCGATAAACTTTACCACTCTTTGCCAACTCAGCCTCTA...,ATGAAGGGGCAAAGAGTAATTTTACAGTCGAGAGGGCTAGCAGTCA...,TACCGCCATCTTCAGCGAACCCTAAAAAGGAGCAAAAGTAAGCTCA...,TAGGGGCTATTAACTTTATTACAACTATTATTAATATGAAAGCCCC...,ENSOCUG00000031196,NaN
1888,0.0,0.0,GL019308,62527,12805,3439,3462,+,+,88228,AATTATTCATAGCCTCAATGATGAACAAGACATCCAAAAAACAGGA...,AATTATTCACAGCCTcaaTGATGAACAGGATATCCGAAAGATAGGC...,GTAGGAATTATATCCTTCCTCCTCATCGGCTGATGGCATGGCCAAG...,ACGTATACATGAGTTGTTCTTACATAATTGAATATACCTGCAATGC...,TGCCTAGGCGCAATCACTACCTTATTCACAGCCCTATGTGCCCTCA...,GTACACCCGTACGCACGCACGTACACCCGTACGCACGCACGTACAC...,ENSOCUG00000037635,NaN
1824,0.0,0.0,AAGW02081594,14016,6061,3040,3073,+,+,24576,TTCTTTGGACACCCTGAGGTATATATTCTTATCCTTCCAGGATTCG...,TTTTTCGGGCACCCCGAAGTATATATTCTTATTCTTCCAGGATTTG...,GACATGTCAAAGGAACGCAGAAGCCAGCTTGAAAAAGTCCTCAACA...,TGAAATAGCTATCACTATTCAGGTATGCCACTATTCTTCTAGGCAT...,ATATGAAAGCCCCTGCAATATCTCAATATCAAACCCCCTTATTCGT...,ATTCTCCTAGGTATCTATTTTACCCTACTTCAAGCATCGGAGTATT...,NaN,NaN

In [31]:
chr_mask=numts['g_id'].apply(lambda g_id: len(g_id) < 3 and g_id!='MT')
numts[chr_mask].head()

,eg2_value,e_value,g_id,g_start,mt_start,g_length,mt_length,g_strand,mt_strand,g_size,g_sequence,mt_sequence,g_up_flanking,g_down_flanking,"mt_up_flanking (if strand is negative, the coordinates are corrected)","mt_down_flanking (if strand is negative, the coordinates are corrected)",ensembl_gene_id,ensembl_description
score,,,,,,,,,,,,,,,,,,
3398,0.000000e+00,0.000000e+00,1,114731432,6976,4680,4681,+,+,194850757,taGTAAAATTATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,TAGTAAAACCATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,ACAAAAGACTCTGAATAGCCAAAGCGATCCTGAACAAGAAAAATCA...,TATATATATTTATATATATATGTATATATGTACATATATATAACTA...,CCTTCGCCTCAAAACGAGAAGTAGAGACTATTGAACTAACAACCAC...,AACTGCTAATTCATGCTCCCATGTCTAACCCCATGGCTTTCTCAAC...,ENSOCUG00000006104,cilia and flagella associated protein 300 [Sou...
457,9.900000e-201,1.700000e-204,18,17579665,9758,1440,1483,+,+,69800736,TAGCACTAATCTTAATTTCCATTCTAGCTGTGTGCTTAGCTTATGA...,TAGCACTTATGTTAATCTCAATCTTAGCCCTTGGATTAGCCTACGA...,CCAGGTGCTTCTCCTGGTCTCCCATGGGGTGCAGGGCCCAAGCACT...,AAGGTGTTACCACTAACAACAACATATGTTGACTGCGAGCAACTAG...,ACTCCCTCAATTAAATATCTATTCAGAAAAATCAAGCCCTTATGAA...,GACTATTCTTCCACTAATAGCAGCATGATGACTAGTTGCTAGCCTT...,NaN,NaN
348,7.600000e-149,1.300000e-152,9,78086277,13328,720,732,+,+,116251907,TTCAACTTCTCTAACCTCTTAGGATTTTTCCCTACAACAATACACC...,TTTAACTTCTCAAACATACTAGGGTTCTTTCCAATGACAATTCATC...,CAAGGTGATCAATGCCTGGGTGTTAGCCCTTAGAGGGTGCAGTGGT...,AGCTACAAATATAACATTTTTATTTATTTATTTATTTTAGAGTTAT...,CTATTAAACGCCTTGCACTAGGAAGCATTTTTGCAGGATTCTTAAT...,CCATCACAAACATTACACTTAATAAAAACACTACGTATGTCATAGT...,ENSOCUG00000000711,KIAA1328 [Source:HGNC Symbol;Acc:HGNC:29248]
267,2.700000e-110,4.800000e-114,12,96965407,17061,419,402,+,+,155355395,TTGGGACTAaacccccctttccccacccccaaaGTCAGGACAGCTC...,TTTGGACTAAACCCCCTTTCCCACCCC----AAGTCAG-ACAGCTC...,CAAATGGATAGATTAAAAAAAAACTAAACTTCAAAAGATGCCAGAA...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,TTTTCCTTTTAACAGGTTTAACTCAATTAAATACAAATTGTATAAT...,ACCACACCCCCAAGGGATACAGCAGTGATAAATATTTAGCAATGAA...,ENSOCUG00000011814,sestrin 1 [Source:HGNC Symbol;Acc:HGNC:21595]
248,3.000000e-101,5.300000e-105,17,53752087,10520,595,597,+,+,85008467,CATTTTCAGCCACCGAATTAATCATAGTTTATATCTTATTCGAAGC...,CATTTTCAGCCACAGAATTTATCCTGTTTTATATTCTATTTGAAGC...,AAAATAGCTAAGGGCAGAGAGTAGAGCTTCCACTTAGCAGTTGAGA...,CATCTTAAAAGCCACAGGCAGATCGTGTAATACTGATTTAGAGAGG...,TAATCAGCCAAGTGACACCAACCTAAACTTCTCAACCACATTTTTT...,GCTTTATAGGCGCCACCGCTCTAATAATCGCACATGGCCTTACTTC...,NaN,NaN

In [38]:
mitos_annotation=pd.read_csv(home_dir+'mitos_annotation.bed', sep='\t', header=False)

TypeError: Passing a bool to header is invalid. Use header=None for no header or header=int or list-like of ints to specify the row(s) making up the column names

In [37]:
mitos_annotation

    MT      0     69   trnF(ttc)     2.761e-12  +
0   MT     69   1026        rrnS  1.600000e-61  +
1   MT   1026   1092   trnV(gta)  1.117000e-10  +
2   MT   1090   2671        rrnL  1.190000e-38  +
3   MT   2671   2746  trnL2(tta)  1.381000e-07  +
4   MT   2748   3699        nad1  2.354573e+08  +
5   MT   3703   3773   trnI(atc)  7.147000e-13  +
6   MT   3770   3842   trnQ(caa)  8.966000e-11  -
7   MT   3850   3919   trnM(atg)  5.601000e-09  +
8   MT   3919   4957        nad2  1.782377e+08  +
9   MT   4970   5037   trnW(tga)  3.962000e-11  +
10  MT   5039   5106   trnA(gca)  5.730000e-11  -
11  MT   5106   5179   trnN(aac)  6.021000e-09  -
12  MT   5211   5280   trnC(tgc)  1.495000e-10  -
13  MT   5280   5346   trnY(tac)  2.304000e-11  -
14  MT   5353   6889        cox1  2.902206e+08  +
15  MT   6897   6966  trnS2(tca)  1.693000e-09  -
16  MT   6969   7038   trnD(gac)  8.457000e-10  +
17  MT   7038   7719        cox2  1.341313e+08  +
18  MT   7725   7794   trnK(aaa)  2.918000e-08  +
19  MT   7795   7990        atp8  1.229856e+06  +
20  MT   7956   8631        atp6  8.400333e+07  +
21  MT   8636   9419        cox3  2.025450e+08  +
22  MT   9420   9490   trnG(gga)  4.192000e-12  +
23  MT   9490   9835        nad3  2.325937e+07  +
24  MT   9837   9904   trnR(cga)  3.514000e-09  +
25  MT   9905  10199       nad4l  1.198647e+07  +
26  MT  10195  11563        nad4  2.592970e+08  +
27  MT  11573  11642   trnH(cac)  7.546000e-09  +
28  MT  11642  11701  trnS1(agc)  8.282000e-06  +
29  MT  11701  11771  trnL1(cta)  1.705000e-15  +
30  MT  11771  13574        nad5  3.159122e+08  +
31  MT  13584  14103        nad6  2.969256e+07  -
32  MT  14103  14171   trnE(gaa)  6.400000e-10  -
33  MT  14174  15308         cob  2.417017e+08  +
34  MT  15313  15379   trnT(aca)  2.538000e-10  +
35  MT  15379  15445   trnP(cca)  2.588000e-12  -