In [1]:
import os
import pandas as pd

In [2]:
home_dir = os.path.join(r'Z:/balint/numt/Michael/data/')

In [3]:
numt_array = pd.read_csv(home_dir + r'numt_master_array_with_1000_flanking.csv')
numt_array = numt_array.drop(0)
numt_array

,score,eg2_value,e_value,g_id,g_start,mt_start,g_length,mt_length,g_strand,mt_strand,g_size,g_sequence,mt_sequence,g_up_flanking,g_down_flanking,"mt_up_flanking (if strand is negative, the coordinates are corrected)","mt_down_flanking (if strand is negative, the coordinates are corrected)"
1,3398,0.000000e+00,0.000000e+00,1,114731432,6976,4680,4681,+,+,194850757,taGTAAAATTATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,TAGTAAAACCATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,GGGCAATTCAATATTCATAAATCAATAAACATCATAAATCACACCA...,TATATATATTTATATATATATGTATATATGTACATATATATAACTA...,GCTTTTAACAGACCGAAACTTAAATACAACCTTCTTTGATCCTGCA...,AACTGCTAATTCATGCTCCCATGTCTAACCCCATGGCTTTCTCAAC...
2,3120,0.000000e+00,0.000000e+00,GL019308,67160,883,4892,4945,+,+,88228,CAAGGCCATGAAGCATGCACACACTGCCCATCGCTCTCCTCAAACA...,CAAGGCCATGAAGCACGCACACACCGCCCGTCACCCTCCTCAAGTG...,AAAGCAATTAAATTTTTAACAAAATTTTTAGGCTTAATGAACTAGA...,ATGAAGGGGCAAAGAGTAATTTTACAGTCGAGAGGGCTAGCAGTCA...,GTTAATGTAGCTTAACAACAAAGCAAAGCACTGAAAATGCTTAGAT...,TAGGGGCTATTAACTTTATTACAACTATTATTAATATGAAAGCCCC...
3,1888,0.000000e+00,0.000000e+00,GL019308,62527,12805,3439,3462,+,+,88228,AATTATTCATAGCCTCAATGATGAACAAGACATCCAAAAAACAGGA...,AATTATTCACAGCCTcaaTGATGAACAGGATATCCGAAAGATAGGC...,TTCTAATTACAGCACTCTACTCCCTCTACATTTTATCAACCAAAGA...,ACGTATACATGAGTTGTTCTTACATAATTGAATATACCTGCAATGC...,TTATTATTTTAGTCCTCCCTATTGTGGCCTCTTTCACTAACATTTT...,GTACACCCGTACGCACGCACGTACACCCGTACGCACGCACGTACAC...
4,1824,0.000000e+00,0.000000e+00,AAGW02081594,14016,6061,3040,3073,+,+,24576,TTCTTTGGACACCCTGAGGTATATATTCTTATCCTTCCAGGATTCG...,TTTTTCGGGCACCCCGAAGTATATATTCTTATTCTTCCAGGATTTG...,TGCCACACCTCCCATGGGATAAAGAGGAAAGGGTCTGGTGCCATGC...,TGAAATAGCTATCACTATTCAGGTATGCCACTATTCTTCTAGGCAT...,CATCTCCTGAGTGCAAACCAGGTGCTTTAATTAAGCTAAATCCTCC...,ATTCTCCTAGGTATCTATTTTACCCTACTTCAAGCATCGGAGTATT...
5,1344,0.000000e+00,0.000000e+00,AAGW02081594,20039,11341,2339,2362,+,+,24576,ATAGCATCCTTTTCATGATCTAATCTCACTATTATTTTAATAGGGA...,ATGGCCTCCTTCTCATGATCTAACCTCACAATCATCCTGATAGGGA...,TCTTTCTCATTGTCCACTGTGCCTGTCAAAAAATAAAAAGAAAAAG...,GGCTGGTGCTGCAGCTCAGTAGGCTAATCTTCCACCTAGCGGCGTG...,CCTAAACTTCTCAACCACATTTTTTTCAGATGCCTTATCCACTCCT...,ATCCTACCTCGTCCCCTTCAAAAACCACCCAATCCCCCATATTTTT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,80,2.800000e-21,5.000000e-25,GL019047,205885,9539,243,247,+,-,247428,GATCAGTTTTCAAAGTGCTTTTATGGTACTGA----AGTACAATAG...,GATCAGTTTTCGAAGTGTTTAAGTGGAACTATTTCGAGGACAATAG...,TTAATTAGATGGCTAAGATTGTGTGTTGAATAAATAGAGTAGTAAT...,AGTTAGGGAGGAGTTGTTAATTTTGTCTGTTATGCATAGAGCTCAT...,CACCTACTATGTAGTAGCTCACTTCCACTATGTCCTATCTATGGGG...,CCTATCTATGATTTAGACTCGCTATGAAGCTAAACAGCGCTAGCCT...
149,77,7.500000e-20,1.300000e-23,AAGW02081404,17858,882,136,140,+,-,27691,GTACGTgcgtacgtgcgtacgggtgtacgggtgtacgggtgtacgg...,gtgcgtacgggtgtacgtgcgtgcgtacgggtgtacgtgcgtgcgt...,TTGTAAAGGTGCGTTTTAAATTTCAAAATTTAGGTGCCCTGAGCTG...,GTACGTGCGTACGTGCGTACGGGTGTACGGGTGTACGTGCGTGCGT...,TGGACAAGTAGCATCTGTCCTCTACTTCACCACCATCCTTATTCTT...,GCACGTACACCCGTACGCACGCACGTACACCCGTACGCACGCACGT...
150,75,6.700000e-19,1.200000e-22,GL019311,22172,5436,218,228,+,-,80506,ATAATTAGTCAAGTTATAGAGGAAGAAAATAG----ATTAGTTTTA...,ATAATTGATACAGCTACAGAGGTGGAGAATAAGTTAATTACTTTTA...,CCCGCGGGTCGTGCGCCAGGTGAGGGCGCAGGTTCGGCCCGGGCCC...,GTTTAAAATGTATGTGCCCTGGGGCTGGCGCGCTGGTGCAGTAGGT...,TCTTATCATTATTACACGATGAGGTAATCAAACAGAGCGACTCAAC...,TATTTTAGTCCTCCCTATTGTGGCCTCTTTCACTAACATTTTTAAT...
151,74,2.000000e-18,3.600000e-22,21,11379492,15954,321,320,+,-,15578276,CTAATTCATTACGTAAAAAGATAAAAGGGTTAATCTTTGCTTTTTA...,CTAATTCATTATGCAAAAGG-TAAGAGAAGTAATCTCTGCTTTTTT...,ATGACAGCCACAGTGAGCACTAAAGTTCTGTTGCACAGAATTGTTT...,GCATGTTTAAGTTTATGATTTAAATTTAAATTAGCTTAGGTTGGCT...,TGGACTAGAAATCTCTAGTCTAGGCTAAAGTTAATGTAGCTTAACA...,CTAGAAAATCCTTAGCAAAAAGAATTTTAGTTAAGAACCCCGAAAC...
152,73,6.000000e-18,1.100000e-21,GL018744,673556,4478,319,330,+,-,2220855,GTGCCTGCAGATGTAGAGAAAAACTGAGTGTGGCTGATTAACGCCA...,GTGGGTGCAGATGTGGAGAAATGCCAGGTGTGGTTGGTTAATTCCG...,GTAGCTCTCACTTTCAAATAAATAAAATAAATCTTTTAAAAAATCT...,ACTACTGCTGTTAGGAGGAGCCGCGTTAATGGGAATGAATCGGGGT...,CAACGAGGCAAATTCACGTATCACACAAACAACATTTCCCCTACAT...,GCCTTCTTCAAAGCTATGCTCTTTCTCTGCTCCGGCTCAATTATTC...

In [4]:
g_ids = numt_array['g_id']
g_ids

1                 1
2          GL019308
3          GL019308
4      AAGW02081594
5      AAGW02081594
           ...
148        GL019047
149    AAGW02081404
150        GL019311
151              21
152        GL018744
Name: g_id, Length: 152, dtype: object

In [5]:
#the start positions of the upstream flankings
u_flanking_start = numt_array['g_start'].apply(lambda start : start - 5000)
u_flanking_start[u_flanking_start < 0] = 0
u_flanking_start.index = g_ids
u_flanking_start

g_id
1               114726432
GL019308            62160
GL019308            57527
AAGW02081594         9016
AAGW02081594        15039
                  ...
GL019047           200885
AAGW02081404        12858
GL019311            17172
21               11374492
GL018744           668556
Name: g_start, Length: 152, dtype: int64

In [6]:
#the end positions of the upstream flankings (which are the genomic_starts of the numts)
u_flanking_end = numt_array['g_start']
u_flanking_end.index = g_ids
u_flanking_end

g_id
1               114731432
GL019308            67160
GL019308            62527
AAGW02081594        14016
AAGW02081594        20039
                  ...
GL019047           205885
AAGW02081404        17858
GL019311            22172
21               11379492
GL018744           673556
Name: g_start, Length: 152, dtype: int64

In [15]:
#start position of downstream_flanking (which is equal to the ends of the numts)
numt_array['g_length'].index = g_ids
d_flanking_start = numt_array['g_start'] + numt_array['g_length']
d_flanking_start.index = g_ids
d_flanking_start

g_id
1               114736112
GL019308            72052
GL019308            65966
AAGW02081594        17056
AAGW02081594        22378
                  ...
GL019047           206128
AAGW02081404        17994
GL019311            22390
21               11379813
GL018744           673875
Length: 152, dtype: int64

In [16]:
#end position of downstream_flanking
numt_ends = numt_array['g_start'] + numt_array['g_length']
d_flanking_end = numt_ends.apply(lambda end : end + 5000)
d_flanking_end

g_id
1               114741112
GL019308            77052
GL019308            70966
AAGW02081594        22056
AAGW02081594        27378
                  ...
GL019047           211128
AAGW02081404        22994
GL019311            27390
21               11384813
GL018744           678875
Length: 152, dtype: int64

In [37]:
def merge_informations(g_id):
    global upstream_flankings
    global downstream_flankings
    u_start = u_flanking_start[g_id]
    u_end = u_flanking_end[g_id]
    d_start = d_flanking_start[g_id]
    d_end = d_flanking_end[g_id]
    upstream_flankings.append([g_id,u_start, u_end])

In [38]:
upstream_flankings = []
g_ids.apply(merge_informations)
upstream_flankings

[['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['GL019308',
  g_id
  GL019308    62160
  GL019308    57527
  GL019308    56116
  GL019308    61326
  GL019308    61343
  Name: g_start, dtype: int64,
  g_id
  GL019308    67160
  GL019308    62527
  GL019308    61116
  GL019308    66326
  GL019308    66343
  Name: g_start, dtype: int64],
 ['GL019308',
  g_id
  GL019308    62160
  GL019308    57527
  GL019308    56116
  GL019308    61326
  GL019308    61343
  Name: g_start, dtype: int64,
  g_id
  GL019308    67160
  GL019308    62527
  GL019308    61116
  GL019308    66326
  GL019308    66343
  Name: g_start, dtype: int64],
 ['AAGW02081594',
  g_id
  AAGW02081594     9016
  AAGW02081594    15039
  AAGW02081594    12085
  AAGW02081594    14087
  Name: g_start, dtype: int64,
  g_id
  AAGW02081594    14016
  AAGW02081594    20039
  AAGW02081594    17085
  AAGW02081594    19087
  Name: g_start, dtype: int64],
 ['AAGW02081594',
  g_id
  AAGW02081594     9016
  AAGW02081594    15039
  AAGW02081594    12085
  AAGW02081594    14087
  Name: g_start, dtype: int64,
  g_id
  AAGW02081594    14016
  AAGW02081594    20039
  AAGW02081594    17085
  AAGW02081594    19087
  Name: g_start, dtype: int64],
 ['GL019326',
  g_id
  GL019326    61435
  GL019326    57422
  GL019326    57558
  GL019326    52446
  GL019326    53863
  GL019326    56315
  Name: g_start, dtype: int64,
  g_id
  GL019326    66435
  GL019326    62422
  GL019326    62558
  GL019326    57446
  GL019326    58863
  GL019326    61315
  Name: g_start, dtype: int64],
 ['AAGW02081594',
  g_id
  AAGW02081594     9016
  AAGW02081594    15039
  AAGW02081594    12085
  AAGW02081594    14087
  Name: g_start, dtype: int64,
  g_id
  AAGW02081594    14016
  AAGW02081594    20039
  AAGW02081594    17085
  AAGW02081594    19087
  Name: g_start, dtype: int64],
 ['GL018741',
  g_id
  GL018741    2307595
  GL018741    2126173
  GL018741    2305815
  GL018741    2125623
  GL018741    2001449
  Name: g_start, dtype: int64,
  g_id
  GL018741    2312595
  GL018741    2131173
  GL018741    2310815
  GL018741    2130623
  GL018741    2006449
  Name: g_start, dtype: int64],
 ['GL019326',
  g_id
  GL019326    61435
  GL019326    57422
  GL019326    57558
  GL019326    52446
  GL019326    53863
  GL019326    56315
  Name: g_start, dtype: int64,
  g_id
  GL019326    66435
  GL019326    62422
  GL019326    62558
  GL019326    57446
  GL019326    58863
  GL019326    61315
  Name: g_start, dtype: int64],
 ['GL019326',
  g_id
  GL019326    61435
  GL019326    57422
  GL019326    57558
  GL019326    52446
  GL019326    53863
  GL019326    56315
  Name: g_start, dtype: int64,
  g_id
  GL019326    66435
  GL019326    62422
  GL019326    62558
  GL019326    57446
  GL019326    58863
  GL019326    61315
  Name: g_start, dtype: int64],
 ['GL019326',
  g_id
  GL019326    61435
  GL019326    57422
  GL019326    57558
  GL019326    52446
  GL019326    53863
  GL019326    56315
  Name: g_start, dtype: int64,
  g_id
  GL019326    66435
  GL019326    62422
  GL019326    62558
  GL019326    57446
  GL019326    58863
  GL019326    61315
  Name: g_start, dtype: int64],
 ['GL019308',
  g_id
  GL019308    62160
  GL019308    57527
  GL019308    56116
  GL019308    61326
  GL019308    61343
  Name: g_start, dtype: int64,
  g_id
  GL019308    67160
  GL019308    62527
  GL019308    61116
  GL019308    66326
  GL019308    66343
  Name: g_start, dtype: int64],
 ['GL018741',
  g_id
  GL018741    2307595
  GL018741    2126173
  GL018741    2305815
  GL018741    2125623
  GL018741    2001449
  Name: g_start, dtype: int64,
  g_id
  GL018741    2312595
  GL018741    2131173
  GL018741    2310815
  GL018741    2130623
  GL018741    2006449
  Name: g_start, dtype: int64],
 ['GL019308',
  g_id
  GL019308    62160
  GL019308    57527
  GL019308    56116
  GL019308    61326
  GL019308    61343
  Name: g_start, dtype: int64,
  g_id
  GL019308    67160
  GL019308    62527
  GL019308    61116
  GL019308    66326
  GL019308    66343
  Name: g_start, dtype: int64],
 ['GL019308',
  g_id
  GL019308    62160
  GL019308    57527
  GL019308    56116
  GL019308    61326
  GL019308    61343
  Name: g_start, dtype: int64,
  g_id
  GL019308    67160
  GL019308    62527
  GL019308    61116
  GL019308    66326
  GL019308    66343
  Name: g_start, dtype: int64],
 ['GL019326',
  g_id
  GL019326    61435
  GL019326    57422
  GL019326    57558
  GL019326    52446
  GL019326    53863
  GL019326    56315
  Name: g_start, dtype: int64,
  g_id
  GL019326    66435
  GL019326    62422
  GL019326    62558
  GL019326    57446
  GL019326    58863
  GL019326    61315
  Name: g_start, dtype: int64],
 ['GL018741',
  g_id
  GL018741    2307595
  GL018741    2126173
  GL018741    2305815
  GL018741    2125623
  GL018741    2001449
  Name: g_start, dtype: int64,
  g_id
  GL018741    2312595
  GL018741    2131173
  GL018741    2310815
  GL018741    2130623
  GL018741    2006449
  Name: g_start, dtype: int64],
 ['18',
  g_id
  18    17574665
  18    69217268
  18    17574018
  18    55868968
  Name: g_start, dtype: int64,
  g_id
  18    17579665
  18    69222268
  18    17579018
  18    55873968
  Name: g_start, dtype: int64],
 ['GL019326',
  g_id
  GL019326    61435
  GL019326    57422
  GL019326    57558
  GL019326    52446
  GL019326    53863
  GL019326    56315
  Name: g_start, dtype: int64,
  g_id
  GL019326    66435
  GL019326    62422
  GL019326    62558
  GL019326    57446
  GL019326    58863
  GL019326    61315
  Name: g_start, dtype: int64],
 ['9',
  g_id
  9    78081277
  9    42948241
  9    63089829
  9    78082323
  Name: g_start, dtype: int64,
  g_id
  9    78086277
  9    42953241
  9    63094829
  9    78087323
  Name: g_start, dtype: int64],
 ['GL018741',
  g_id
  GL018741    2307595
  GL018741    2126173
  GL018741    2305815
  GL018741    2125623
  GL018741    2001449
  Name: g_start, dtype: int64,
  g_id
  GL018741    2312595
  GL018741    2131173
  GL018741    2310815
  GL018741    2130623
  GL018741    2006449
  Name: g_start, dtype: int64],
 ['AAGW02081594',
  g_id
  AAGW02081594     9016
  AAGW02081594    15039
  AAGW02081594    12085
  AAGW02081594    14087
  Name: g_start, dtype: int64,
  g_id
  AAGW02081594    14016
  AAGW02081594    20039
  AAGW02081594    17085
  AAGW02081594    19087
  Name: g_start, dtype: int64],
 ['12',
  g_id
  12    96960407
  12    96960610
  12     9549534
  Name: g_start, dtype: int64,
  g_id
  12    96965407
  12    96965610
  12     9554534
  Name: g_start, dtype: int64],
 ['GL018705', 1443740, 1448740],
 ['17',
  g_id
  17    53747087
  17    16995447
  17    62650313
  Name: g_start, dtype: int64,
  g_id
  17    53752087
  17    17000447
  17    62655313
  Name: g_start, dtype: int64],
 ['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['GL018700', 6976609, 6981609],
 ['9',
  g_id
  9    78081277
  9    42948241
  9    63089829
  9    78082323
  Name: g_start, dtype: int64,
  g_id
  9    78086277
  9    42953241
  9    63094829
  9    78087323
  Name: g_start, dtype: int64],
 ['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['9',
  g_id
  9    78081277
  9    42948241
  9    63089829
  9    78082323
  Name: g_start, dtype: int64,
  g_id
  9    78086277
  9    42953241
  9    63094829
  9    78087323
  Name: g_start, dtype: int64],
 ['GL018741',
  g_id
  GL018741    2307595
  GL018741    2126173
  GL018741    2305815
  GL018741    2125623
  GL018741    2001449
  Name: g_start, dtype: int64,
  g_id
  GL018741    2312595
  GL018741    2131173
  GL018741    2310815
  GL018741    2130623
  GL018741    2006449
  Name: g_start, dtype: int64],
 ['19', 3084165, 3089165],
 ['GL019465',
  g_id
  GL019465        0
  GL019465    11513
  GL019465     5439
  GL019465    10341
  GL019465     7861
  Name: g_start, dtype: int64,
  g_id
  GL019465     3878
  GL019465    16513
  GL019465    10439
  GL019465    15341
  GL019465    12861
  Name: g_start, dtype: int64],
 ['12',
  g_id
  12    96960407
  12    96960610
  12     9549534
  Name: g_start, dtype: int64,
  g_id
  12    96965407
  12    96965610
  12     9554534
  Name: g_start, dtype: int64],
 ['GL019465',
  g_id
  GL019465        0
  GL019465    11513
  GL019465     5439
  GL019465    10341
  GL019465     7861
  Name: g_start, dtype: int64,
  g_id
  GL019465     3878
  GL019465    16513
  GL019465    10439
  GL019465    15341
  GL019465    12861
  Name: g_start, dtype: int64],
 ['9',
  g_id
  9    78081277
  9    42948241
  9    63089829
  9    78082323
  Name: g_start, dtype: int64,
  g_id
  9    78086277
  9    42953241
  9    63094829
  9    78087323
  Name: g_start, dtype: int64],
 ['GL018817',
  g_id
  GL018817    630509
  GL018817    626156
  GL018817    623929
  GL018817    629326
  Name: g_start, dtype: int64,
  g_id
  GL018817    635509
  GL018817    631156
  GL018817    628929
  GL018817    634326
  Name: g_start, dtype: int64],
 ['13',
  g_id
  13    70572587
  13    15102645
  Name: g_start, dtype: int64,
  g_id
  13    70577587
  13    15107645
  Name: g_start, dtype: int64],
 ['GL018826',
  g_id
  GL018826    325095
  GL018826    407531
  GL018826    133737
  GL018826    135154
  GL018826    409131
  GL018826    135815
  GL018826    133018
  GL018826    404745
  Name: g_start, dtype: int64,
  g_id
  GL018826    330095
  GL018826    412531
  GL018826    138737
  GL018826    140154
  GL018826    414131
  GL018826    140815
  GL018826    138018
  GL018826    409745
  Name: g_start, dtype: int64],
 ['GL018748',
  g_id
  GL018748    1126178
  GL018748    1141326
  GL018748    1132760
  Name: g_start, dtype: int64,
  g_id
  GL018748    1131178
  GL018748    1146326
  GL018748    1137760
  Name: g_start, dtype: int64],
 ['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['GL018817',
  g_id
  GL018817    630509
  GL018817    626156
  GL018817    623929
  GL018817    629326
  Name: g_start, dtype: int64,
  g_id
  GL018817    635509
  GL018817    631156
  GL018817    628929
  GL018817    634326
  Name: g_start, dtype: int64],
 ['GL019465',
  g_id
  GL019465        0
  GL019465    11513
  GL019465     5439
  GL019465    10341
  GL019465     7861
  Name: g_start, dtype: int64,
  g_id
  GL019465     3878
  GL019465    16513
  GL019465    10439
  GL019465    15341
  GL019465    12861
  Name: g_start, dtype: int64],
 ['GL018817',
  g_id
  GL018817    630509
  GL018817    626156
  GL018817    623929
  GL018817    629326
  Name: g_start, dtype: int64,
  g_id
  GL018817    635509
  GL018817    631156
  GL018817    628929
  GL018817    634326
  Name: g_start, dtype: int64],
 ['2',
  g_id
  2    154325735
  2     38018391
  Name: g_start, dtype: int64,
  g_id
  2    154330735
  2     38023391
  Name: g_start, dtype: int64],
 ['18',
  g_id
  18    17574665
  18    69217268
  18    17574018
  18    55868968
  Name: g_start, dtype: int64,
  g_id
  18    17579665
  18    69222268
  18    17579018
  18    55873968
  Name: g_start, dtype: int64],
 ['17',
  g_id
  17    53747087
  17    16995447
  17    62650313
  Name: g_start, dtype: int64,
  g_id
  17    53752087
  17    17000447
  17    62655313
  Name: g_start, dtype: int64],
 ['7',
  g_id
  7    103877371
  7     49546495
  7    126581487
  Name: g_start, dtype: int64,
  g_id
  7    103882371
  7     49551495
  7    126586487
  Name: g_start, dtype: int64],
 ['GL018817',
  g_id
  GL018817    630509
  GL018817    626156
  GL018817    623929
  GL018817    629326
  Name: g_start, dtype: int64,
  g_id
  GL018817    635509
  GL018817    631156
  GL018817    628929
  GL018817    634326
  Name: g_start, dtype: int64],
 ['GL019465',
  g_id
  GL019465        0
  GL019465    11513
  GL019465     5439
  GL019465    10341
  GL019465     7861
  Name: g_start, dtype: int64,
  g_id
  GL019465     3878
  GL019465    16513
  GL019465    10439
  GL019465    15341
  GL019465    12861
  Name: g_start, dtype: int64],
 ['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['GL019465',
  g_id
  GL019465        0
  GL019465    11513
  GL019465     5439
  GL019465    10341
  GL019465     7861
  Name: g_start, dtype: int64,
  g_id
  GL019465     3878
  GL019465    16513
  GL019465    10439
  GL019465    15341
  GL019465    12861
  Name: g_start, dtype: int64],
 ['18',
  g_id
  18    17574665
  18    69217268
  18    17574018
  18    55868968
  Name: g_start, dtype: int64,
  g_id
  18    17579665
  18    69222268
  18    17579018
  18    55873968
  Name: g_start, dtype: int64],
 ['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['17',
  g_id
  17    53747087
  17    16995447
  17    62650313
  Name: g_start, dtype: int64,
  g_id
  17    53752087
  17    17000447
  17    62655313
  Name: g_start, dtype: int64],
 ['16', 72412467, 72417467],
 ['1',
  g_id
  1    114726432
  1     75605052
  1     75606658
  1    172056750
  1     75611882
  1     75612250
  1     75614486
  1     75750940
  1     75748972
  Name: g_start, dtype: int64,
  g_id
  1    114731432
  1     75610052
  1     75611658
  1    172061750
  1     75616882
  1     75617250
  1     75619486
  1     75755940
  1     75753972
  Name: g_start, dtype: int64],
 ['GL018786', 212688, 217688],
 ['13',
  g_id
  13    70572587
  13    15102645
  Name: g_start, dtype: int64,
  g_id
  13    70577587
  13    15107645
  Name: g_start, dtype: int64],
 ['7',
  g_id
  7    103877371
  7     49546495
  7    126581487
  Name: g_start, dtype: int64,
  g_id
  7    103882371
  7     49551495
  7    126586487
  Name: g_start, dtype: int64],
 ['7',
  g_id
  7    103877371
  7     49546495
  7    126581487
  Name: g_start, dtype: int64,
  g_id
  7    103882371
  7     49551495
  7    126586487
  Name: g_start, dtype: int64],
 ['GL018706', 3433128, 3438128],
 ['12',
  g_id
  12    96960407
  12    96960610
  12     9549534
  Name: g_start, dtype: int64,
  g_id
  12    96965407
  12    96965610
  12     9554534
  Name: g_start, dtype: int64],
 ['4',
  g_id
  4    17868977
  4    13249816
  4    13251500
  4    13248305
  4    13254345
  4    13254345
  4    13253434
  4    35266214
  Name: g_start, dtype: int64,
  g_id
  4    17873977
  4    13254816
  4    13256500
  4    13253305
  4    13259345
  4    13259345
  4    13258434
  4    35271214
  Name: g_start, dtype: int64],
 ['AAGW02081404',
  g_id
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12083
  AAGW02081404    11756
  AAGW02081404    11930
  AAGW02081404    12236
  AAGW02081404    11778
  AAGW02081404    12389
  AAGW02081404    11778
  AAGW02081404    12928
  AAGW02081404    12948
  AAGW02081404        0
  AAGW02081404    12542
  AAGW02081404        0
  AAGW02081404    11778
  AAGW02081404    12970
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12984
  AAGW02081404    13010
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12858
  AAGW02081404        0
  AAGW02081404    12858
  AAGW02081404    12858
  Name: g_start, dtype: int64,
  g_id
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    17083
  AAGW02081404    16756
  AAGW02081404    16930
  AAGW02081404    17236
  AAGW02081404    16778
  AAGW02081404    17389
  AAGW02081404    16778
  AAGW02081404    17928
  AAGW02081404    17948
  AAGW02081404      374
  AAGW02081404    17542
  AAGW02081404        0
  AAGW02081404    16778
  AAGW02081404    17970
  AAGW02081404        5
  AAGW02081404      394
  AAGW02081404      322
  AAGW02081404    17984
  AAGW02081404    18010
  AAGW02081404      422
  AAGW02081404      322
  AAGW02081404      322
  AAGW02081404      466
  AAGW02081404      442
  AAGW02081404    17858
  AAGW02081404      322
  AAGW02081404    17858
  AAGW02081404    17858
  Name: g_start, dtype: int64],
 ['AAGW02081404',
  g_id
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12083
  AAGW02081404    11756
  AAGW02081404    11930
  AAGW02081404    12236
  AAGW02081404    11778
  AAGW02081404    12389
  AAGW02081404    11778
  AAGW02081404    12928
  AAGW02081404    12948
  AAGW02081404        0
  AAGW02081404    12542
  AAGW02081404        0
  AAGW02081404    11778
  AAGW02081404    12970
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12984
  AAGW02081404    13010
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12858
  AAGW02081404        0
  AAGW02081404    12858
  AAGW02081404    12858
  Name: g_start, dtype: int64,
  g_id
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    17083
  AAGW02081404    16756
  AAGW02081404    16930
  AAGW02081404    17236
  AAGW02081404    16778
  AAGW02081404    17389
  AAGW02081404    16778
  AAGW02081404    17928
  AAGW02081404    17948
  AAGW02081404      374
  AAGW02081404    17542
  AAGW02081404        0
  AAGW02081404    16778
  AAGW02081404    17970
  AAGW02081404        5
  AAGW02081404      394
  AAGW02081404      322
  AAGW02081404    17984
  AAGW02081404    18010
  AAGW02081404      422
  AAGW02081404      322
  AAGW02081404      322
  AAGW02081404      466
  AAGW02081404      442
  AAGW02081404    17858
  AAGW02081404      322
  AAGW02081404    17858
  AAGW02081404    17858
  Name: g_start, dtype: int64],
 ['AAGW02081404',
  g_id
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12083
  AAGW02081404    11756
  AAGW02081404    11930
  AAGW02081404    12236
  AAGW02081404    11778
  AAGW02081404    12389
  AAGW02081404    11778
  AAGW02081404    12928
  AAGW02081404    12948
  AAGW02081404        0
  AAGW02081404    12542
  AAGW02081404        0
  AAGW02081404    11778
  AAGW02081404    12970
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12984
  AAGW02081404    13010
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404        0
  AAGW02081404    12858
  AAGW02081404        0
  AAGW02081404    12858

In [39]:
upstream_flankings[0][1]

g_id
1    114726432
1     75605052
1     75606658
1    172056750
1     75611882
1     75612250
1     75614486
1     75750940
1     75748972
Name: g_start, dtype: int64

In [42]:
upstream_flankings[0][2].tolist()

[114731432,
 75610052,
 75611658,
 172061750,
 75616882,
 75617250,
 75619486,
 75755940,
 75753972]

In [48]:
upstream_flankings[0][1], upstream_flankings[0][2]

(g_id
 1    114726432
 1     75605052
 1     75606658
 1    172056750
 1     75611882
 1     75612250
 1     75614486
 1     75750940
 1     75748972
 Name: g_start, dtype: int64,
 g_id
 1    114731432
 1     75610052
 1     75611658
 1    172061750
 1     75616882
 1     75617250
 1     75619486
 1     75755940
 1     75753972
 Name: g_start, dtype: int64)

In [55]:
df = pd.DataFrame(upstream_flankings[0][1]).transpose()
df

g_id,1,1,1,1,1,1,1,1,1
g_start,114726432,75605052,75606658,172056750,75611882,75612250,75614486,75750940,75748972