In [57]:
import numpy as np
import pandas as pd
from Bio import pairwise2

In [2]:
numts=pd.read_csv('../../results/3numt_array.csv')
numts.head(n=5)

,score,eg2_value,e_value,g_id,g_start,mt_start,g_length,mt_length,g_strand,mt_strand,g_size,g_sequence,mt_sequence,g_up_flanking,g_down_flanking,"mt_up_flanking (if strand is negative, the coordinates are corrected)","mt_down_flanking (if strand is negative, the coordinates are corrected)",ensembl_gene_id,ensembl_description
0,3398,0.0,0.0,1,114731432,6976,4680,4681,+,+,194850757,taGTAAAATTATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,TAGTAAAACCATTACATAACTTTGTCGAAGTTAATTTATAGGTTCA...,ACAAAAGACTCTGAATAGCCAAAGCGATCCTGAACAAGAAAAATCA...,TATATATATTTATATATATATGTATATATGTACATATATATAACTA...,CCTTCGCCTCAAAACGAGAAGTAGAGACTATTGAACTAACAACCAC...,AACTGCTAATTCATGCTCCCATGTCTAACCCCATGGCTTTCTCAAC...,ENSOCUG00000006104,cilia and flagella associated protein 300 [Sou...
1,3120,0.0,0.0,GL019308,67160,883,4892,4945,+,+,88228,CAAGGCCATGAAGCATGCACACACTGCCCATCGCTCTCCTCAAACA...,CAAGGCCATGAAGCACGCACACACCGCCCGTCACCCTCCTCAAGTG...,GATAAACCCCGATAAACTTTACCACTCTTTGCCAACTCAGCCTCTA...,ATGAAGGGGCAAAGAGTAATTTTACAGTCGAGAGGGCTAGCAGTCA...,TACCGCCATCTTCAGCGAACCCTAAAAAGGAGCAAAAGTAAGCTCA...,TAGGGGCTATTAACTTTATTACAACTATTATTAATATGAAAGCCCC...,ENSOCUG00000031196,NaN
2,1888,0.0,0.0,GL019308,62527,12805,3439,3462,+,+,88228,AATTATTCATAGCCTCAATGATGAACAAGACATCCAAAAAACAGGA...,AATTATTCACAGCCTcaaTGATGAACAGGATATCCGAAAGATAGGC...,GTAGGAATTATATCCTTCCTCCTCATCGGCTGATGGCATGGCCAAG...,ACGTATACATGAGTTGTTCTTACATAATTGAATATACCTGCAATGC...,TGCCTAGGCGCAATCACTACCTTATTCACAGCCCTATGTGCCCTCA...,GTACACCCGTACGCACGCACGTACACCCGTACGCACGCACGTACAC...,ENSOCUG00000037635,NaN
3,1824,0.0,0.0,AAGW02081594,14016,6061,3040,3073,+,+,24576,TTCTTTGGACACCCTGAGGTATATATTCTTATCCTTCCAGGATTCG...,TTTTTCGGGCACCCCGAAGTATATATTCTTATTCTTCCAGGATTTG...,GACATGTCAAAGGAACGCAGAAGCCAGCTTGAAAAAGTCCTCAACA...,TGAAATAGCTATCACTATTCAGGTATGCCACTATTCTTCTAGGCAT...,ATATGAAAGCCCCTGCAATATCTCAATATCAAACCCCCTTATTCGT...,ATTCTCCTAGGTATCTATTTTACCCTACTTCAAGCATCGGAGTATT...,NaN,NaN
4,1344,0.0,0.0,AAGW02081594,20039,11341,2339,2362,+,+,24576,ATAGCATCCTTTTCATGATCTAATCTCACTATTATTTTAATAGGGA...,ATGGCCTCCTTCTCATGATCTAACCTCACAATCATCCTGATAGGGA...,CCAAGTACTTAGCCTGGTCTCCCATGGGGTGCAGGGCCCAAGCACT...,GGCTGGTGCTGCAGCTCAGTAGGCTAATCTTCCACCTAGCGGCGTG...,TAATCGCACATGGCCTTACTTCCTCATTATTATTCTGCCTAGCCAA...,ATCCTACCTCGTCCCCTTCAAAAACCACCCAATCCCCCATATTTTT...,NaN,NaN

In [3]:
alignments=pd.read_csv('../../data/filtered_alignments.csv',index_col=0)
alignments.head(n=5)

,score,chr_id,chr_start,chr_no_letters,chr_strand,chr_size,scf_id,scf_start,scf_no_letters,scf_strand,scf_size,blocks,EG2_val,E-val
61902,79,14.0,5159068.0,422.0,+,163896628.0,GL019308,18580.0,448.0,-,88228.0,"72,0:3,27,0:2,122,0:19,68,0:1,100,0:1,33",EG2=8.4e-21,E=2.7e-24
1505873,40,14.0,5159511.0,243.0,+,163896628.0,GL018741,1655521.0,219.0,+,2352391.0,"74,21:0,37,1:0,30,2:0,78",EG2=0.031,E=0.00026
5179730,104,14.0,5159515.0,238.0,+,163896628.0,GL018705,5295519.0,235.0,+,6124611.0,"130,1:0,36,2:0,69",EG2=1.1e-32,E=2.4e-34
36807789,60,14.0,5159511.0,190.0,+,163896628.0,GL018706,2938370.0,182.0,+,5787221.0,"110,3:0,14,1:0,16,3:0,26,1:0,16",EG2=9.2e-12,E=2e-13
40825691,60,14.0,5159508.0,245.0,+,163896628.0,GL018706,871592.0,245.0,-,5787221.0,"57,0:1,80,1:0,107",EG2=9.2e-12,E=2e-13

In [4]:
alignments.loc[alignments['chr_id']==2].sort_values(by='chr_start')

,score,chr_id,chr_start,chr_no_letters,chr_strand,chr_size,scf_id,scf_start,scf_no_letters,scf_strand,scf_size,blocks,EG2_val,E-val
41715403,77,2.0,38023391.0,240.0,+,174332312.0,AAGW02081404,12646.0,235.0,+,27691.0,"65,2:0,107,1:0,19,2:0,44",EG2=7.5e-20,E=7.5e-24
42042964,93,2.0,38023391.0,273.0,+,174332312.0,GL019525,7105.0,271.0,+,45853.0,"60,1:0,130,1:0,81",EG2=1.8e-27,E=3e-31
41990745,85,2.0,38023391.0,273.0,+,174332312.0,GL019383,43977.0,267.0,+,64055.0,"60,1:0,130,5:0,77",EG2=1.2e-23,E=2.7e-27
41870693,83,2.0,38023391.0,273.0,+,174332312.0,GL019056,193570.0,267.0,+,204766.0,"60,1:0,130,5:0,77",EG2=1e-22,E=7.8e-26
41750495,89,2.0,38023391.0,273.0,+,174332312.0,GL019271,54933.0,270.0,+,89743.0,"60,1:0,140,2:0,70",EG2=1.5e-25,E=4.7e-29
42323788,97,2.0,38023391.0,275.0,+,174332312.0,GL018925,436904.0,273.0,+,588789.0,"60,1:0,130,1:0,83",EG2=2.3e-29,E=4.9e-32
60585,84,2.0,38023391.0,256.0,+,174332312.0,GL019308,17852.0,250.0,-,88228.0,"61,1:0,129,5:0,60",EG2=3.5e-23,E=1.1e-26
42113877,97,2.0,38023403.0,261.0,+,174332312.0,GL019149,135745.0,259.0,+,139324.0,"48,1:0,130,1:0,81",EG2=2.3e-29,E=1.1e-32
41715503,137,2.0,154330735.0,325.0,+,174332312.0,AAGW02081404,4303.0,326.0,-,27691.0,"79,0:1,246",EG2=2.1e-48,E=2.1e-52
41715504,137,2.0,154330735.0,325.0,+,174332312.0,AAGW02081404,21842.0,326.0,-,27691.0,"79,0:1,246",EG2=2.1e-48,E=2.1e-52
973522,103,2.0,154330746.0,314.0,+,174332312.0,GL018741,2312875.0,314.0,+,2352391.0,"72,0:1,94,1:0,147",EG2=3.1e-32,E=2.7e-34
87907,110,2.0,154330746.0,314.0,+,174332312.0,AAGW02081594,19272.0,306.0,+,24576.0,"69,7:0,170,1:0,67",EG2=1.5e-35,E=1.3e-39
27482943,68,2.0,154330813.0,170.0,+,174332312.0,GL019465,16725.0,171.0,+,51331.0,"56,0:1,114",EG2=1.4e-15,E=2.7e-19
27903366,68,2.0,154330813.0,170.0,+,174332312.0,GL018817,635721.0,171.0,+,947161.0,"56,0:1,114",EG2=1.4e-15,E=5e-18
27482942,68,2.0,154330813.0,170.0,+,174332312.0,GL019465,4090.0,171.0,+,51331.0,"56,0:1,114",EG2=1.4e-15,E=2.7e-19
121787,103,2.0,154330814.0,464.0,+,174332312.0,GL019326,57504.0,468.0,+,81722.0,"110,1:0,125,0:3,31,0:2,38,6:0,95,0:1,35,0:5,23",EG2=3.1e-32,E=9.4e-36
20262,89,2.0,154330814.0,246.0,+,174332312.0,GL019308,61174.0,241.0,+,88228.0,"173,5:0,68",EG2=1.5e-25,E=4.7e-29

In [6]:
numts.loc[numts['g_id']=='2'].sort_values(by='g_start')

,score,eg2_value,e_value,g_id,g_start,mt_start,g_length,mt_length,g_strand,mt_strand,g_size,g_sequence,mt_sequence,g_up_flanking,g_down_flanking,"mt_up_flanking (if strand is negative, the coordinates are corrected)","mt_down_flanking (if strand is negative, the coordinates are corrected)",ensembl_gene_id,ensembl_description
136,93,1.800000e-27,3.200000e-31,2,38023391,13115,273,271,+,-,174332312,TTATGTGTATAAATGCAGTTGCTTTGTTTAAGAAATATTTGACAGC...,TTAAGATTATAGATGCTGTGGCTTGTGTTAGAAAATACTTGGTTGC...,ATTAGCAGGGAGCTGAATTAGAAGTGGAGCGGCTGGGACTCGAACC...,AATGCTTGAAGCAGCTCAAAAGTCTTTCCTGCGACTCATTTCTTCT...,TATCTCAATGCCTATCATACTTTCAAGTATCCCTCCTCAGATATAG...,TAATAGCTATTACACTTAATATCCTTGACTCCGGACAATGAACCCT...,NaN,NaN
44,137,2.100000e-48,3.700000e-52,2,154330735,10943,325,326,+,+,174332312,TCAGCCTCTTAACAGACTATTTAGTGAATCCGTTCCTCAACTTGTT...,TCAGCCCTATTACAGACTATATAGCCTACCCATTCCTCATACTCTC...,AGCATTATTTTACATCTCAAGTTCAACAGGATCATTAAAATTTTTA...,ATACAGCTAAGTTTGATTAACAGTCATACGATAACTGTCAGTCTAA...,TAAATCCATTACAACATCGTGATCAAACTCACTGATATGACTAGCA...,TGACTAGTTGCTAGCCTTACCAACCTGGCCCTACCTCCAACTATTA...,ENSOCUG00000005878,mediator of cell motility 1 [Source:HGNC Symbo...

In [11]:
alignments.loc[alignments['chr_id']==2].sort_values(by='chr_start').head()

,score,chr_id,chr_start,chr_no_letters,chr_strand,chr_size,scf_id,scf_start,scf_no_letters,scf_strand,scf_size,blocks,EG2_val,E-val
41715403,77,2.0,38023391.0,240.0,+,174332312.0,AAGW02081404,12646.0,235.0,+,27691.0,"65,2:0,107,1:0,19,2:0,44",EG2=7.5e-20,E=7.5e-24
42042964,93,2.0,38023391.0,273.0,+,174332312.0,GL019525,7105.0,271.0,+,45853.0,"60,1:0,130,1:0,81",EG2=1.8e-27,E=3e-31
41990745,85,2.0,38023391.0,273.0,+,174332312.0,GL019383,43977.0,267.0,+,64055.0,"60,1:0,130,5:0,77",EG2=1.2e-23,E=2.7e-27
41870693,83,2.0,38023391.0,273.0,+,174332312.0,GL019056,193570.0,267.0,+,204766.0,"60,1:0,130,5:0,77",EG2=1e-22,E=7.8e-26
41750495,89,2.0,38023391.0,273.0,+,174332312.0,GL019271,54933.0,270.0,+,89743.0,"60,1:0,140,2:0,70",EG2=1.5e-25,E=4.7e-29

In [70]:
seq1='AAATCTCGGCTATTAGGCGCTCTGACTCTCGCGTATGGGTTTTTCCTTCTCA'
seq2='ATCCGTATCTCGGCTATTAGACGCTCTGACTCTCGCGTATGGGTTCCCCTCCTTCTCA'
pairwise2.align.globalms(seq1,seq2,1,-1,-7,-1,one_alignment_only=True)[0].score

26.0

In [71]:
alignments.head()

,score,chr_id,chr_start,chr_no_letters,chr_strand,chr_size,scf_id,scf_start,scf_no_letters,scf_strand,scf_size,blocks,EG2_val,E-val
61902,79,14.0,5159068.0,422.0,+,163896628.0,GL019308,18580.0,448.0,-,88228.0,"72,0:3,27,0:2,122,0:19,68,0:1,100,0:1,33",EG2=8.4e-21,E=2.7e-24
1505873,40,14.0,5159511.0,243.0,+,163896628.0,GL018741,1655521.0,219.0,+,2352391.0,"74,21:0,37,1:0,30,2:0,78",EG2=0.031,E=0.00026
5179730,104,14.0,5159515.0,238.0,+,163896628.0,GL018705,5295519.0,235.0,+,6124611.0,"130,1:0,36,2:0,69",EG2=1.1e-32,E=2.4e-34
36807789,60,14.0,5159511.0,190.0,+,163896628.0,GL018706,2938370.0,182.0,+,5787221.0,"110,3:0,14,1:0,16,3:0,26,1:0,16",EG2=9.2e-12,E=2e-13
40825691,60,14.0,5159508.0,245.0,+,163896628.0,GL018706,871592.0,245.0,-,5787221.0,"57,0:1,80,1:0,107",EG2=9.2e-12,E=2e-13

In [72]:
len(alignments)

431