In [1]:
import pandas as pd

In [4]:
pd.read_csv(r'Z:\balint\numt\Michael\data/1_repeats (2)', sep = '\t')

,#bin,swScore,milliDiv,milliDel,milliIns,genoName,genoStart,genoEnd,genoLeft,strand,repName,repClass,repFamily,repStart,repEnd,repLeft,id
0,1123,1434,171,0,0,chr1,70610113,70610347,-124240410,-,CSINE1,SINE,SINE,-106,234,1,1
1,1123,28,0,0,0,chr1,70610351,70610379,-124240378,+,AT_rich,Low_complexity,Low_complexity,1,28,0,1
2,1123,636,160,0,0,chr1,70610415,70610515,-124240242,+,CSINE2,SINE,SINE,175,274,-70,1
3,1123,1277,174,151,20,chr1,70610518,70610817,-124239940,-,CSINE2,SINE,SINE,-6,338,1,1
4,1123,3237,265,68,31,chr1,70610817,70612196,-124238561,+,L1MD,LINE,L1,3584,5013,-1133,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10008,1161,3569,196,60,6,chr1,75608106,75608902,-119241855,-,L1M3,LINE,L1,-1303,4837,3999,1
10009,1161,1788,157,62,9,chr1,75609201,75609522,-119241235,-,CSINE2,SINE,SINE,-5,339,2,1
10010,1161,305,217,0,135,chr1,75609555,75609629,-119241128,-,CSINE2,SINE,SINE,-51,293,229,1
10011,1161,2077,122,36,30,chr1,75609629,75609966,-119240791,+,CSINE1,SINE,SINE,1,339,-1,1
10012,1161,305,217,0,135,chr1,75609966,75609987,-119240770,-,CSINE2,SINE,SINE,-116,228,211,1