In [1]:
import pandas as pd

In [2]:
#Reads the csv file
data = pd.read_csv(r"C:\Users\micha\Documents\Thesis\GitHub\numt\results\lastal_array_duplicates_removed.csv")

In [5]:
#If mt_start and mt_length exceed the size of the mtDNA it will assume the numt is overarching
overarching_numts = data.drop(data[(data.mt_start+data.mt_length)<=17245].index).sort_values('mt_start')
overarching_numts

,score,eg2_value,e_value,g_id,g_start,mt_start,g_length,mt_length,g_strand,mt_strand,g_size,g_sequence,mt_sequence
65,16742,0.000000e+00,0.000000e+00,AAGW02081404,0,476,17391,17405,+,-,27691,GGGTTTAGTCCAAATATTATACAATTTGTATTTAAATTGAGTTATC...,GGGTTTAGTCCAAATATTATACAATTTGTATTTAA-TTGAGTTAAA...
80,572,1.800000e-255,3.100000e-259,4,13259345,16374,998,994,+,-,91394100,CTCTATTCTTAATTTACTTCTAAATCCTCCTTTAGCCCTTAACATT...,CTCTATTCTTAATTTACTACTAAATCCTCCTTTGGCCCTTAGAGTT...
23,267,2.700000e-110,4.800000e-114,12,96965407,17061,419,402,+,+,155355395,TTGGGACTAaacccccctttccccacccccaaaGTCAGGACAGCTC...,TTTGGACTAAACCCCCTTTCCCACCCC----AAGTCAG-ACAGCTC...
9,942,0.000000e+00,0.000000e+00,GL019326,62422,17114,1451,1466,+,+,81722,tttttcaatttaaaaAGCACCTTCACAATACTGACATAGCACTCTA...,TTTTGAAATTTAAAACGCACCTTTACAATACTGACATAGCACTCTA...
14,591,1.600000e-264,2.800000e-268,GL019308,66326,17228,837,857,+,+,88228,CTCTAACCCAGGCCTAAGTGAATGTAGCTTAACAGTAAAGCAAAGC...,CTCTAGTCTAGGCTAAAGTTAATGTAGCTTAACAACAAAGCAAAGC...
66,16135,0.000000e+00,0.000000e+00,AAGW02081404,0,17721,16756,16769,+,-,27691,GGGTTTAGTCCAAATATTATACAATTTGTATTTAAATTGAGTTATC...,GGGTTTAGTCCAAATATTATACAATTTGTATTTAA-TTGAGTTAAA...
82,556,7.500000e-248,1.300000e-251,4,13259345,33619,866,871,+,-,91394100,CTCTATTCTTAATTTACTTCTAAATCCTCCTTTAGCCCTTAACATT...,CTCTATTCTTAATTTACTACTAAATCCTCCTTTGGCCCTTAGAGTT...